// ! Export Constants for Authenticated related Actions
export const authConstants = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGOUT_REQUEST: "LOGOUT_REQUEST",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAILURE: "LOGOUT_FAILURE",
};

// ! Export Constants for Registration related Actons
export const userConstants = {
  USER_REGISTRATION_REQ: "USER_REGISTRATION_REQ",
  USER_REGISTRATION_SUCCESS: "USER_REGISTRATION_SUCCESS",
  USER_REGISTRATION_FAILURE: "USER_REGISTRATION_FAILURE",
};

// ! Export Constants for category related Actons
export const categoryConstants = {
  GET_ALL_CATEGORIES_REQ: "GET_ALL_CATEGORIES_REQ",
  GET_ALL_CATEGORIES_SUCCESS: "GET_ALL_CATEGORIES_SUCCESS",
  GET_ALL_CATEGORIES_FAILURE: "GET_ALL_CATEGORIES_FAILURE",
  ADD_NEW_CATEGORIES_REQ: "ADD_NEW_CATEGORIES_REQ",
  ADD_NEW_CATEGORIES_SUCCESS: "ADD_NEW_CATEGORIES_SUCCESS",
  ADD_NEW_CATEGORIES_FAILURE: "ADD_NEW_CATEGORIES_FAILURE",
};
