// ! Export Constants for Authenticated related Actions
export const authConstants = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGOUT_REQUEST: "LOGOUT_REQUEST",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAILURE: "LOGOUT_FAILURE",
};

// ! Export Constants for Registration related Actons
export const userConstants = {
  USER_REGISTRATION_REQ: "USER_REGISTRATION_REQ",
  USER_REGISTRATION_SUCCESS: "USER_REGISTRATION_SUCCESS",
  USER_REGISTRATION_FAILURE: "USER_REGISTRATION_FAILURE",
};

// ! Export Constants for category related Actons
export const categoryConstants = {
  GET_ALL_CATEGORIES_REQ: "GET_ALL_CATEGORIES_REQ",
  GET_ALL_CATEGORIES_SUCCESS: "GET_ALL_CATEGORIES_SUCCESS",
  GET_ALL_CATEGORIES_FAILURE: "GET_ALL_CATEGORIES_FAILURE",

  ADD_NEW_CATEGORIES_REQ: "ADD_NEW_CATEGORIES_REQ",
  ADD_NEW_CATEGORIES_SUCCESS: "ADD_NEW_CATEGORIES_SUCCESS",
  ADD_NEW_CATEGORIES_FAILURE: "ADD_NEW_CATEGORIES_FAILURE",

  UPDATE_CATEGORIES_REQ: "UPDATE_CATEGORIES_REQ",
  UPDATE_CATEGORIES_SUCCESS: "UPDATE_CATEGORIES_SUCCESS",
  UPDATE_CATEGORIES_FAILURE: "UPDATE_CATEGORIES_FAILURE",

  DELETE_CATEGORIES_REQ: "DELETE_CATEGORIES_REQ",
  DELETE_CATEGORIES_SUCCESS: "DELETE_CATEGORIES_SUCCESS",
  DELETE_CATEGORIES_FAILURE: "DELETE_CATEGORIES_FAILURE",
};

// ! Export Constants for product related Actions
export const productConstants = {
  GET_ALL_PRODUCTS_REQ: "GET_ALL_PRODUCTS_REQ",
  GET_ALL_PRODUCTS_SUCCESS: "GET_ALL_PRODUCTS_SUCCESS",
  GET_ALL_PRODUCTS_FAILURE: "GET_ALL_PRODUCTS_FAILURE",
  // ADD_NEW_CATEGORIES_REQ: "ADD_NEW_CATEGORIES_REQ",
  // ADD_NEW_CATEGORIES_SUCCESS: "ADD_NEW_CATEGORIES_SUCCESS",
  // ADD_NEW_CATEGORIES_FAILURE: "ADD_NEW_CATEGORIES_FAILURE",
};

export const pageConstants = {
  CREATE_PAGE_REQUEST: "CREATE_PAGE_REQUEST",
  CREATE_PAGE_SUCCESS: "CREATE_PAGE_SUCCESS",
  CREATE_PAGE_FAILURE: "CREATE_PAGE_FAILURE",
};

export const orderConstants = {
  GET_CUSTOMER_ORDER_REQUEST: "GET_CUSTOMER_ORDER_REQUEST",
  GET_CUSTOMER_ORDER_SUCCESS: "GET_CUSTOMER_ORDER_SUCCESS",
  GET_CUSTOMER_ORDER_FAILURE: "GET_CUSTOMER_ORDER_FAILURE",
};