
// ! Export Constants for category related Actons
export const categoryConstants = {
  GET_ALL_CATEGORIES_REQ: "GET_ALL_CATEGORIES_REQ",
  GET_ALL_CATEGORIES_SUCCESS: "GET_ALL_CATEGORIES_SUCCESS",
  GET_ALL_CATEGORIES_FAILURE: "GET_ALL_CATEGORIES_FAILURE",
};

// ! Export Constants for product related Actons
export const productConstants = {
  //GET_PRODUCTS_BY_SLUG_REQ: "GET_PRODUCTS_BY_SLUG_REQ",
  GET_PRODUCTS_BY_SLUG_SUCCESS: "GET_PRODUCTS_BY_SLUG_SUCCESS",
 // GET_PRODUCTS_BY_SLUG_FAILURE: "GETPRODUCTS_BY_SLUGS_FAILURE",
};