
// ! Export Constants for category related Actons
export const categoryConstants = {
  GET_ALL_CATEGORIES_REQ: "GET_ALL_CATEGORIES_REQ",
  GET_ALL_CATEGORIES_SUCCESS: "GET_ALL_CATEGORIES_SUCCESS",
  GET_ALL_CATEGORIES_FAILURE: "GET_ALL_CATEGORIES_FAILURE",
  ADD_NEW_CATEGORIES_REQ: "ADD_NEW_CATEGORIES_REQ",
  ADD_NEW_CATEGORIES_SUCCESS: "ADD_NEW_CATEGORIES_SUCCESS",
  ADD_NEW_CATEGORIES_FAILURE: "ADD_NEW_CATEGORIES_FAILURE",
};
